VERSION: 1
dataset:
    batch_size: 6
    datapath: '*/path/to/data'
    name: 'DatasetName'
    trainlist: '*/path/to/data/train.txt'
    testlist: '*/path/to/data/test.txt'
    workers: 4
input:
    size: (224, 224)
kd:
    enable: 0
    loss:
        alpha: 0.2
        temperature: 2
    model:
        name: 'teacher_net_name'
        path: 'teacher_net.pt'
label_transforms:
    name: 'default'
logger:
    log_file: '.'
    log_frequency: 100
    name: ''
    path: ''
loss:
    CrossEntropy:
        class_weight: []
    name: 'CrossEntropy'
model:
    aux_weight: 0.4
    classes: 10
    depth: 5
    dropout_rate: 0.5
    expansion: 2
    in_channels: 3
    name: 'ClsNet'
    num_layers: 6
    num_nodes: 4
    out_channels: 32
    resume_path: ''
    use_aux_heads: True
mutator:
    EnasMutator:
        arch_loss_weight: 0.02
        branch_bias: 0.25
        cell_exit_extra_step: False
        lstm_num_layers: 2
        lstm_size: 64
        reward_function: ''
        reward_weight: 50
        skip_target: 0.4
        tanh_constant: 1.5
    name: 'EnasMutator'
optim.scheduler:
    milestones: [10, 20, 30]
    t_max: 50
    name: 'cosineannealinglr'
optimizer:
    lr: 0.001
    momentum: 0.9
    name: 'adam'
    weight_decay: 0.0005
output_root: './outputs'
trainer:
    EnasTrainer:
        baseline_decay: 0.999
        entropy_weight: 0.1
        mutator_lr: 0.001
        mutator_steps: 50
        mutator_steps_aggregate: 20
        skip_weight: 0.8
    accumulate_steps: 1
    device: 'cuda'
    device_ids: [0, 1, 2]
    name: 'EnasTrainer'
    num_epochs: 50
    startEpoch: 0
    startRound: 0
    warm_start_epoch: -1
transforms:
    img:
        aug_cifar: False
        aug_imagenet: False
        center_crop:
            enable: 0
        color_jitter:
            brightness: 0.05
            contrast: 0.05
            enable: 0
            hue: 0.05
            saturation: 0.05
        random_crop:
            enable: 1
            padding: 0
        random_horizontal_flip:
            enable: 1
            p: 0.5
        random_resized_crop:
            enable: 0
            ratio: (0.75, 1.3333333333333333)
            scale: (0.5, 1.0)
        random_rotation:
            degrees: 5
            enable: 1
        random_vertical_flip:
            enable: 1
            p: 0.5
        resize:
            enable: 1
    name: 'DefaultTransforms'
    tensor:
        normalization:
            mean: [0.6075, 0.4564, 0.4182]
            std: [0.2158, 0.1871, 0.1826]
        random_erasing:
            enable: 0
            p: 0.5
            ratio: ((0.3, 3.3),)
            scale: (0.02, 0.3)
